### ISSUE TITLE
minor changes UF

### ISSUE THREAD

**Issue by Querxer** [TheLoneTec/Hardcore-SK#1]
since Verse.AI.ToilFailConditions.FailOnDespawnedNullOrForbiddenPlacedThings have been rewritten in 1.4

some minor fix is needed at

JobDriver_FillUF.MakeNewToils
```
...
yield return gotoBillGiver;
yield return Toils_General.Wait(this.Fermenter.DefUF.fillDelay, TargetIndex.A)
				.FailOnDespawnedNullOrForbiddenPlacedThings(TargetIndex.None)
...

```
TargetIndex.None should be replaced by TargetIndex.B

**Comment by TheLoneTec** [comment]
are you sure your on the latest version? i do not have this in mine.

**Comment by TheLoneTec** [comment]
hmm i see its not been updated on the github

**Comment by TheLoneTec** [comment]
Fixed in latest Commit
