### ISSUE TITLE
tree felling RW 1.4

### ISSUE THREAD

**Issue by Querxer** [TheLoneTec/Hardcore-SK#11]
there is a questionable new feature by 1.4 
after tree was cut there is remains a stump

at that moment we are cutting a trees without stumps

**Comment by TheLoneTec** [comment]
are you saying trees arent leaving stumps?

**Comment by Querxer** [comment]
yep

**Comment by TheLoneTec** [comment]
kinda want to say thats a feature ;) but yeah, should probably check it out.

**Comment by TheLoneTec** [comment]
this should be fixed in the enxt update, the SK Trees were missing some new tags

**Comment by Querxer** [comment]
yeah
it looks so tiresome
unlikely cattleya will be drawing stumps for each type of a tree )

**Comment by TheLoneTec** [comment]
if it looks too out of place, im sure someone will make some textures for them. I could even do it, but im a little bust at the moment.
