### ISSUE TITLE
Mech Gestator Not Detecting Metals (Solids, Ultrasolids) in Stockpiles

### ISSUE THREAD

**Issue by Arkaile** [TheLoneTec/Hardcore-SK#11]
Both the regular and large mech gestator do not appear to be detecting any solids or ultrasolids which are in stockpiles, but are detecting other materials such as carbon, components, circuits, etc. The gestator's UI has the items listed in blue as though they are available, but when I try to assign a mechanitor to work on it, I get a message saying that ingredients, specifically solids and ultrasolids, are missing. There are no additional mods or patches installed, this is just a fresh installation of the HSK mod pack and there don't seem to be any errors in the log associated to this issue. It appears to be affecting all the mechs, not just those shown in the captures.

![gestator issue 1](https://user-images.githubusercontent.com/73376008/208214039-b682f3de-33a3-4ad2-a42e-efe71a8b354b.PNG)
![gestator issue 2](https://user-images.githubusercontent.com/73376008/208214043-46d4e5bc-fe66-4362-8e95-88558549ee55.PNG)
![gestator issue 3](https://user-images.githubusercontent.com/73376008/208214045-497226d6-c4b9-4b18-a89e-a8d8f8828c27.PNG)
![gestator issue 4](https://user-images.githubusercontent.com/73376008/208214049-47ce7684-d460-421d-a9e7-728cada15d51.PNG)

**Comment by OranolAron** [comment]
I fixed this with the Make Anything Craftable mod. The craft itself is registered, but apparently not activated.

**Comment by OranolAron** [comment]
I fixed this with the Make Anything Craftable mod. The craft itself is registered, but apparently not activated.

**Comment by TheLoneTec** [comment]
Sorry been sick the last 3 days, still technically am, but feeling better, will look into it.

**Comment by TheLoneTec** [comment]
hmm its wierd, the vanilla one doesnt have any defaultIngredientFilters, yet works, perhaps its a recipe mod in hsk that is stopping it, ill add in the filters to see if that fixes it.

**Comment by TheLoneTec** [comment]
Fix for this in the latest commit. Replace the 2 patches with the new ones and it should now work.
