### ISSUE TITLE
suddenly crashed 

### ISSUE THREAD

**Issue by Querxer** [TheLoneTec/Hardcore-SK#12]
nothing suspicious for me
only the spammed message 
Debug Message:Bill_MakeSteelBars_Hand_24
[Player_crash.log](https://github.com/TheLoneTec/Hardcore-SK/files/10050272/Player_crash.log)

**Comment by Querxer** [comment]
Debug Message:Bill_MakeSteelBars_Hand_24
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Message (string)
ImprovedWorkbenches.RecipeWorkerCounter_CountProducts_Detour:Postfix (Verse.RecipeWorkerCounter&,int&,RimWorld.Bill_Production&)
(wrapper dynamic-method) Verse.RecipeWorkerCounter:Verse.RecipeWorkerCounter.CountProducts_Patch2 (Verse.RecipeWorkerCounter,RimWorld.Bill_Production)
RimWorld.Bill_Production:ShouldDoNow ()
RimWorld.BillStack:get_AnyShouldDoNow ()
SK.CompFueled:get_ShouldWork ()
SK.CompFueled:get_IsWorking ()
SK.CompFueled:InstantlyAdjustInternalTemp ()
SK.CompFueled:CompTick ()
Verse.ThingWithComps:Tick ()
Verse.TickList:Tick ()
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch0 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) Verse.Game:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
Verse.Root_Play:Update ()

**Comment by TheLoneTec** [comment]
ah yes, i added that debug message to check it was the method i thought it was that was causing that RecipeWorkerCounter error

**Comment by TheLoneTec** [comment]
it shouldnt be spamming though, ill see if i can fix that
