### ISSUE TITLE
Cut Tree Designation Over Stump Crashes Game

### ISSUE THREAD

**Issue by TheLoneTec** [TheLoneTec/Hardcore-SK#18]
For now, do not drag select over any stumps using the "Cut Tree" designation. It will freeze and close your game.

**Comment by masakitenchi** [comment]
```CS
[HarmonyPatch(typeof(Designator_Plants))]
[HarmonyPatch("CanDesignateThing")]
public class Patch_Designator_Plants_CanDesignateThing
{
	public static bool Prefix(Designator_Plants __instance, ref AcceptanceReport __result, Thing t)
	{
		Log.Message("Prefixing");
		if (t != null && (!t.Position.InBounds(__instance.Map) || t.Position.Fogged(__instance.Map)))
		{
			__result = false;
			return false;
		}
		return true;
	}
}```
Seems to be prefix's problem. Also Inbounds and fogged usually throws NullReferenceException when selecting something for the first time. Will open another issue for that.

**Comment by masakitenchi** [comment]
```CS
public class Patch_Designator_Plants_CanDesignateThing
{
	public static bool Prefix(Designator_Plants __instance, ref AcceptanceReport __result, Thing t)
	{
		Log.Message("Prefixing");
		if(t != null)
        {
			Log.Message($"Selecting {t.def.defName}");
			if (!t.Position.InBounds(__instance.Map) || t.Position.Fogged(__instance.Map))
			{
				__result = false;
				return false;
			}

		}
		/*if (t != null && (!t.Position.InBounds(__instance.Map) || t.Position.Fogged(__instance.Map)))
		{
			__result = false;
			return false;
		}*/
		return true;
	}
}
```
When selecting smashed stomp, the log are spammed by:
`Prefixing
Selecting SmashedStumpBig
Prefixing
Selecting SmashedStumpBig
Prefixing
Selecting SmashedStumpBig
Prefixing
Selecting SmashedStumpBig
`
May be because stack over flow.

**Comment by TheLoneTec** [comment]
i did try removing this method and it still did it, perhaps the assembly didnt get compiled when i tried it. But also, This may not bee needed any more as the same code is present in vanilla

**Comment by TheLoneTec** [comment]
can confirm its not this code. removing it doesnt stop the crash. It seems to be something that gets called in the vanilla code for the selection code, as its generating the visual (before the mouse button is released) that something can be selected where it crashes.

**Comment by TheLoneTec** [comment]
Fixed in latest
