### ISSUE TITLE
Combat Extended Targeting, wont select head or automatic

### ISSUE THREAD

**Issue by Querxer** [TheLoneTec/Hardcore-SK#2]
gunner skilled to 10 and more 
can't aim for the head

**Comment by masakitenchi** [comment]
Used a prefix like this:
`public static bool ChangeTargetModePrefix(ref CompFireModes __instance)
        {
            Log.Message($"Current target mode:{__instance.targetMode}");
            switch(__instance.targetMode)
            {
                case TargettingMode.torso:
                    __instance.targetMode = TargettingMode.head;
                    break;
                case TargettingMode.head:
                    __instance.targetMode = TargettingMode.automatic;
                    break;
                case TargettingMode.automatic:
                    __instance.targetMode = TargettingMode.legs;
                    break;
                case TargettingMode.legs:
                    __instance.targetMode = TargettingMode.torso;
                    break;
            }
            return false;
        }`
And each click generates two message:
![image](https://user-images.githubusercontent.com/11086210/211234769-fefd2c86-5ab7-4666-a880-a7eca77d761f.png)
So the action is actually triggered twice. But where does that trigger another time is yet to be found.

**Comment by masakitenchi** [comment]
Confirmed problem is Gizmo Duplication.
RimWorld.InspectGizmoGrid.gizmoList is already duplicated after calling Pawn.GetGizmos.
```XML
<Pawn.GetGizmos>
    <ThingWithComps.GetGizmos>
        <Thing.GetGizmos>
            <ContainintSelectionUtility.SelectContainingThingGizmo> <!--Newly added in 1.4?-->
            <IdeologyRitualGizmos>
        </Thing.GetGizmos>
        <comps.CompGetGizmosExtra>
    </ThingWithComps.GetGizmos>
    <Pawn.drafter.GetGizmos/>
    <PawnAttackGizmoUtility.GetAttackGizmos/>
    <Pawn.equipment.GetGizmos/>
    <Pawn.carryTracker.GetGizmos/>
    <Pawn.needs.GetGizmos/>
    <Pawn.psychicEntropy.NeedToShowGizmo/>           <!--Royalty needed-->
    <MechanitorUtility.GetMechGizmos/>   <!--Biotech needed-->
    <Pawn.mechanoid.GetGizmos/>     <!--Biotech needed-->
    <Pawn.GrowthTier.GetGizmos/>    <!--Biotech needed-->
    <Pawn.abilities.GetGizmos/>
    <Pawn.playerSettings.GetGizmos/>
    <Pawn.health.GetGizmos/>
    <Pawn.apparel.GetGizmos/>
    <Pawn.inventory.GetGizmos/>
    <Pawn.mindState.GetGizmos/>
    <allFactionPermit.Permit.Worker.GetPawnGizmos/> <!--Royalty needed-->
    <Pawn.royalty.RoyalAidGizmo/>   <!--Royalty needed-->
    <permit.Worker.GetPawnGizmos/>  <!--Royalty needed-->
    <QuestUtility.GetQuestRelatedGizmos/>
    <Pawn.royalty.RoyalAidGizmo/>   <!--Royalty needed-->
    <Pawn.connections.GetGizmos/>   <!--Ideology needed-->
    <Pawn.genes.GetGizmos/> <!--Biotech needed-->
    <lord.LordJob.GetPawnGizmos/>
    <lord.CurLordToil.GetPawnGizmos/>
    <BioTechDevGizmos/>
</Pawn.GetGizmos>
```
Remember, Vanilla code runs normally with CE, so Vanilla code probably won't be the problem.
My harmony patches that's related to keyword **Gizmo**:
![image](https://user-images.githubusercontent.com/11086210/211321356-7343b224-578a-4ccd-ba32-a21963d1fe11.png)
Will check through each mod to find the true problem.

**Comment by TheLoneTec** [comment]
Fixed in latest
