### ISSUE TITLE
SK Closeable Vent

### ISSUE THREAD

**Issue by TheLoneTec** [TheLoneTec/Hardcore-SK#22]
https://discord.com/channels/272340793174392832/283226662970195969/1065960394843234364

**Comment by masakitenchi** [comment]
![image](https://user-images.githubusercontent.com/11086210/221068508-9df8b6f7-9a41-48d5-946b-ee85cbbed116.png)
Skywrath controller also have this problem

**Comment by masakitenchi** [comment]
Plasma reactor
![image](https://user-images.githubusercontent.com/11086210/221997423-b8ddae31-c2c6-4be9-b16c-4e8f7d5fcf1c.png)

**Comment by TheLoneTec** [comment]
possibly fixed in upcoming commit
