### ISSUE TITLE
Mechlink

### ISSUE THREAD

**Issue by Zasteria** [TheLoneTec/Hardcore-SK#3]
A mechanic with the Mechlink health feature - cannot go into combat mode. Button does not respond. Without this trait, the colonist can switch to Combat mode.
https://gist.github.com/058bef618cafd02951cc00a1bf280824

**Comment by Zasteria** [comment]
> A mechanic with the Mechlink health feature - cannot go into combat mode. Button does not respond. Without this trait, the colonist can switch to Combat mode. https://gist.github.com/058bef618cafd02951cc00a1bf280824
The headset has no armor characteristics.

**Comment by TheLoneTec** [comment]
this seems to be a graphical error. will look into it.

**Comment by TheLoneTec** [comment]
I cant seem to figure out whats causing this issue. As no one else seems to be reporting this, its going to take a while to figure out.

**Comment by TheLoneTec** [comment]
Fixed in latest commit. The comms console was missing 2 comps that are used to summon the mechanitor first boss.
