### ISSUE TITLE
marble snow rock has a wrong texture

### ISSUE THREAD

**Issue by Querxer** [TheLoneTec/Hardcore-SK#5]
Mods\Minerals\Textures\Things\Rock\WeatheredMarble\WeatheredMarbleD_s.png
has a lava texture
<img width="369" alt="lavaRocks" src="https://user-images.githubusercontent.com/77893852/201530757-86b64946-176c-414f-b25d-adf4f10e49bc.png">

**Comment by TheLoneTec** [comment]
fixed
