### ISSUE TITLE
Mod Androids

### ISSUE THREAD

**Issue by SuperDIMMaX** [TheLoneTec/Hardcore-SK#6]
https://github.com/TheLoneTec/Hardcore-SK/commit/cde5bc52875528b87853b1ee445d8d719e50be9e#diff-37f8df4a733f655260503691ed243f385a2c5ff576ab99e4d56453a3fc3721d9R533

```
			<li Class="Androids.MechanicalPawnProperties">
				<!-- If true the pawn will not lose any skill due to decay. -->
				<noSkillLoss>true</noSkillLoss>
				<!-- Can this Droid be social? -->
				<canSocialize>false</canSocialize>
				<!-- Do the colony care if they die? -->
				<colonyCaresIfDead>false</colonyCaresIfDead>
			</li>
```

Are you sure? or this is Ctrl-C Ctrl-V from Droids?

and androids now have constant `ChJDroidAlways`

**Comment by TheLoneTec** [comment]
this has been corrected, thanks for submitting
